### PR TITLE
Auth( UI & Functionality )

### PR DESCRIPTION
**Pull request by nubiv**

### CODE REVIEW

**Comment by Devansh-365** [comment]
I think we can also add a toast component for notification when user sign in or create account.  Also it might also use again when user upload images of events and get notified after photos upload.

**Comment by nubiv** [comment]
> I think we can also add a toast component for notification when user sign in or create account. Also it might also use again when user upload images of events and get notified after photos upload.

Yes we need a toast component to deal with notifications.
BTW current user hook is unnecessary since user data will be saved in the session after successful login. NextAuth has a useSession hook to retrieve session data.

**Comment by Devansh-365** [comment]
> 

While developing when I am sign-in your credentials is showing I think it's because we sign in at same time. I though by doing that the problem will get resolved.

Also it's possible I might be wrong so feel free to remove the api endpoint and hook.

**Comment by nubiv** [comment]
> > 
> 
> While developing when I am sign-in your credentials is showing I think it's because we sign in at same time. I though by doing that the problem will get resolved.
> 
> Also it's possible I might be wrong so feel free to remove the api endpoint and hook.

Yea earlier on your credentials were poping up on my local once. Let's see if that error still persists.

**Review by Devansh-365 — APPROVED** [review]

**Review by Pixelshot — APPROVED** [review]

**Pull request merged**
